### ISSUE TITLE
Napkin Diagram for Project 1

### ISSUE THREAD

**Issue by dhruti-patel** [airavata-courses/ampersand#1]
Creating an issue as a todo for Napkin Diagram for our Project 1

**Comment by kamblenikhil** [comment]
Link - https://docs.google.com/drawings/d/1quBTYMuoOw65fReGc6xFH8s6j1LrNmrRBFlPTb03w8M/edit?usp=sharing

Partially complete!

**Comment by dhruti-patel** [comment]
Updated the napkin diagram in wiki

**Comment by dhruti-patel** [comment]
https://github.com/airavata-courses/ampersand/wiki/Home/95d80e1d9b9870783b62dceeddc64c373e4d210a
