### ISSUE TITLE
Add Wiki Page for project milestone 1

### ISSUE THREAD

**Issue by dhruti-patel** [airavata-courses/ampersand#10]

**Comment by dhruti-patel** [comment]
All the deployment information added to wiki

**Comment by dhruti-patel** [comment]
https://github.com/airavata-courses/ampersand/wiki/Home/95d80e1d9b9870783b62dceeddc64c373e4d210a

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/70fa9d2be31ad006e4b5db22035386a0ba6996bf
