### ISSUE TITLE
Bug fixes and testing

### ISSUE THREAD

**Issue by apednek** [airavata-courses/ampersand#26]

**Comment by apednek** [comment]
https://github.com/airavata-courses/ampersand/commit/83cf77ab0e2ade5dc836894fae48729665ca7126

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/83cf77ab0e2ade5dc836894fae48729665ca7126

**Comment by apednek** [comment]
https://github.com/airavata-courses/ampersand/commit/6d56be954e754858764fd28d9d964ec5f0014f65
