### ISSUE TITLE
Project 1 feedback by Team Zilean

### ISSUE THREAD

**Issue by RushikeshPharate** [airavata-courses/ampersand#28]
- Making a separate release branch was very thoughtful it makes life easy. 
- Detailed user-managed and user requests. Also, the system architecture is very efficient. UI looks great and detailed. 
- Implementing Google Auth is commendable.
- One improvement that can be done is adding pagination.

Thanks,
Team Zilean

**Comment by dhruti-patel** [comment]
We will try to incorporate pagination in our further milestones. Thanks for the feedback!!
