### ISSUE TITLE
Project Review - Orion

### ISSUE THREAD

**Issue by orangatun** [airavata-courses/ampersand#29]
Hello team,

We ran your project, and encountered a few minor inconveniences which should be quick fixes:

#### Markdown suggestion
Consider using code blocks to set instructions instead of quote blocks. 
```
cd account-service && npm i && npm start
```

> cd account-service
npm I
npm start

#### Port already in use

When we ran the project as is, we encountered the port already in use, and the program exited. 

```
Port 5000 is already in use
```

Suggested running command:

```
PORT = 5001 npm start
```

## greetings-services microservice

It was straightforward, and we encountered no issues running this microservice.

## data-ingestor microservice

We encountered a minor issue on one of our machines while running the `pip install -r requirements.txt` command due to existing packages and conflicts. The docker method worked without smoothly and got us going. Dockerizing this microservice was a good idea. 

## data-plotting microservice

Running this microservice was easy, and it worked cleanly with docker. 

## radar-station microservice

This microservice ran successfully with the build process. A suggested improvement would be add the maven commands to run this directly, without Eclipse. In our case, it was not an issue because we already had an installation of Eclipse on our machines. 

## database microservice

We tried running this microservice on macOS, and faced issues with a fresh installation of mongoDB. It does however run on a windows machine. 

---

Overall, minor inconveniences aside, great work!

\- Team Orion

**Comment by dhruti-patel** [comment]
Using "&&" to run multiple commands at once is a great idea. We could not give the liberty of choosing the port number because currently the API Gateway is configured to hit the account-service on port 5000. But we will try to find some workaround this in our future project milestones. Thanks for the feedback!!

**Comment by kamblenikhil** [comment]
Thank you for your feedback. We really appreciate your valuable time.

1. Those are some really interesting insights/suggestions and we will definitely work on those. Our next step is to make an easy installation process (probably using docker compose). 
2. Regarding the Database microservice - We haven't tested this particular microservice on Mac (Linux) based machines. We will work on that particular issue too.

- Team Ampersand
