### ISSUE TITLE
Build basic frontend to take user query input

### ISSUE THREAD

**Issue by dhruti-patel** [airavata-courses/ampersand#4]
https://www.ncdc.noaa.gov/nexradinv/displaygraphs.jsp?mm=01&dd=01&yyyy=2021&product=CCL3N2V&filter=&id=KIND

**Comment by kamblenikhil** [comment]
Link - https://brython.info/index.html

1. Is it recommeded to display our python code at client-side for displaying the graph?

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/84d8d3c965a55f2e379313bd1af0f33ec69a223c

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/84d8d3c965a55f2e379313bd1af0f33ec69a223c

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/c6223da9016988c13a96656b0eb0a7604c9ec856
