### ISSUE TITLE
Build API gateway

### ISSUE THREAD

**Issue by dhruti-patel** [airavata-courses/ampersand#8]

**Comment by kamblenikhil** [comment]
adding additional routes

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/c6223da9016988c13a96656b0eb0a7604c9ec856

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/4c5a32df2bb57d0ba0d6969811834868ec7c0c0f

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/144f89a7c70a1247453bd65a3fae7af78bba8612

**Comment by kamblenikhil** [comment]
https://github.com/airavata-courses/ampersand/commit/83cf77ab0e2ade5dc836894fae48729665ca7126
